name: C/C++ CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: build
      run: g++ -std=c++20 -O2 -Wall -Wextra -I. EKF.cpp Simulation.cpp -o ekf_sim
